# Workflow that tests the validity of the DockerFile
name: Docker Image Build
on:
  pull_request:
    paths:
      - 'Dockerfile'
      - 'tests/requirements.txt'
  push:
    branches: [ "main" ]
    paths:
      - 'Dockerfile'
      - 'tests/requirements.txt'

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3
      with:
        path: wifi-power-meas-test
        fetch-depth: 0

    - name: Build the Docker image
      working-directory: wifi-power-meas-test
      run: docker build . --file Dockerfile --tag wifi-power-meas-test:test

