name: Pycodestyle

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          pip3 install pycodestyle

      - name: Run pycodestyle
        run: |
          python3 -m pycodestyle . --max-line-length=100