name: Test

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    runs-on: self-hosted
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    container:
      image: ghcr.io/balaji-nordic/wifi-power-meas-test:v0.0.1
      options: -v /dev/:/dev --privileged -e PPK_PORT -e DK_PORT
    env:
      CMAKE_PREFIX_PATH: /opt/toolchains
    steps:
      - name: Cleanup workspace
        run: |
          rm -rf ./*
          rm -rf ./.??*

      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: wifi-power-meas-test

      - name: Initialize
        working-directory: wifi-power-meas-test
        run: |
          west init -l .
          west update -o=--depth=1 -n

      - name: Run tests
        working-directory: wifi-power-meas-test/tests/
        run: |
          export ZEPHYR_BASE=$(pwd)/../../zephyr
          pytest -v --log-cli-level=DEBUG

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: wifi-power-meas-test/tests/test_results

      - name: Set write permissions
        if: ${{ always() }}
        run: |
          chmod 777 -R ./* | true
          chmod 777 -R ./.??* | true
